# Generated by Django 4.2.4 on 2023-08-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like', 'like'), ('comment', 'comment'), ('follow', 'follow'), ('welcome', 'welcome')], max_length=20)),
                ('arg_value', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('viewed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
